// IMPORTS
import { type Prefixed_UUID, generatePrefixedUUID } from '$lib/utils/uuid';
import { type Image } from '$lib/utils/types/image';

// CHARACTER CLASS
export class Character {
	id: Prefixed_UUID<'character'> = generatePrefixedUUID('character');
	name: string = 'New Character';
	avatar: Image = this.setDefaultAvatar();

	constructor(name?: string) {
		if (name) {
			this.name = name;
		}
	}

	private setDefaultAvatar(): Image {
		return {
			title: this.name,
			url: `https://robohash.org/${this.name}`,
			license: 'cc',
			caption: 'Avatar generated by RoboHash,org',
			source: 'https://robohash.org',
			alt: `Avatar for ${this.name}`
		};
	}
}
